djangoApp/urls.py
from django.contrib import admin
from django.urls import include, path

# Urlpatterns global to the project are set here, e.g. the path to the urls 
# of the application leadsDatabase and the urls of the admin page.
urlpatterns = [
    path('', include('leadsDatabase.urls')),
    path('admin/', admin.site.urls),
]

leadsDatabase/urls.py
from django.urls import path

from . import views

# As this project contains only one app, namespacing the urls is not strictly necessary.
# However, in this way it becomes scalable for whatever we might add later on.
app_name = 'leadsDatabase'

# We have the main url and two suburls with the list and add pages.
urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.list, name='list'),
    path('add', views.add, name='add'),
    path('addResult', views.addResult, name='addResult'),
]

leadsDatabase/models.py
from django.db import models

# In this case the model consists of the name of a lead and its email adress.
class Lead(models.Model):
    name_text = models.CharField('Lead name', max_length=60)
    email_text = models.EmailField('Lead Email', max_length=254)
    def __str__(self):
        return self.name_text

leadsDatabase/views.py
from django.shortcuts import get_object_or_404, render
from .models import Lead

# Defines the index view, i.e. the welcome page.
def index(request):
    return render(request, 'leadsDatabase/index.html')

# Returns the list of all entries in the Lead model ordered by their name.
def list(request):
    leads = Lead.objects.order_by('-name_text')[:]
    context = {
        'leads' : leads,
    }
    return render(request, 'leadsDatabase/list.html', context)

# Returns the template page for the add lead form.
def add(request):
    return render(request, 'leadsDatabase/add.html')

# The function, that actually handles the adding of a lead.
def addResult(request):
    # Gets the data from the POST method.
    leadName = request.POST.__getitem__('leadName')
    leadEmail = request.POST.__getitem__('leadEmail')

    # Used for error handling.
    error = False
    errorMessage = ''

    # Creates a new lead with the retrieved values for its name and email.
    lead = Lead(name_text=leadName, email_text=leadEmail)

    # Checks if the lead exists already and if name and email were given.abs
    # The check for uniqueness is done only with the email adress.
    if(Lead.objects.filter(email_text=leadEmail).exists() and leadName != "" and leadEmail != ""):
        error = True
        errorMessage = 'Your Email adress is already in our database.'
    elif(leadName == "" and leadEmail != ""):
        error = True
        errorMessage = 'Please provide a name as well.'
    elif(leadEmail == "" and leadName != ""):
        error = True
        errorMessage = 'Please provide an Email adress as well.'
    elif(leadEmail == "" and leadName == ""):
        error = True
        errorMessage = 'Please provide a name and an Email adress.'
    else:
        # If everything is valid, the lead is saved into the database.
        lead.save()
    
    # Provides the names to be used inside the template html file addResult.html
    context = {
        'leadName' : leadName,
        'leadEmail' : leadEmail,
        'error' : error,
        'errorMessage' : errorMessage
    }
    return render(request, 'leadsDatabase/addResult.html', context)

leadsDatabase/templates/leadsDatabase/add.html
{% extends "leadsDatabase/base.html" %}

{% block mainContainer %}

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <div id="formContainer">
        <form action="{% url 'leadsDatabase:addResult' %}" method="post">
            {% csrf_token %} <!-- Protection against Cross Site Forgery -->   
            <label>Name: </label><input type=text name="leadName" id="leadNameInput" /><br />
            <label>Email: </label><input type="email" name="leadEmail" id="leadEmailInput" /><br />
            <input id="inputButtonAddLead" type="submit" value="Add new lead" />
        </form>
        <form action='{% url "leadsDatabase:index" %}'>
            <input id="inputButtonGoBack"  type="submit" value="Go back to main page" />
        </form>
    </div>

{% endblock %}

leadsDatabase/templates/leadsDatabase/addResult.html
{% extends "leadsDatabase/base.html" %}

{% block mainContainer %}

    <!-- Error is set to true or false in the views.py addResult function. If true, the 
          error message will be shown. --> 
    {% if error %}
        <div class="errorMessages">
            An error occured.<br />
            {{ errorMessage }}
        </div>
    {% else %}
        <!-- Creates a table with the just added lead. -->
        <table class="leadsTable">
            <tr>
                <th class="leadTableHeaders">Name</th>
                <th class="leadTableHeaders">Email adress</th>
            </tr>
            <tr>
                <td class="leadTableEntries">{{ leadName }}</td>
                <td class="leadTableEntries">{{ leadEmail }}</td>
            </tr>
        </table>
    {% endif %}
    <!-- Includes the buttons to add another lead or go back to the welcome page. -->
    {% include 'leadsDatabase/inputButtons.html' %}
{% endblock %}

leadsDatabase/templates/leadsDatabase/base.html
<!-- Enables loading static files, e.g. a stylesheet.-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'leadsDatabase/style.css' %}" />
    <title>{% block title %} List or add leads! {% endblock %}</title>
</head>

<body>
    <div id="mainContainer">
        <!-- Block for the actual page. Is filled by all the child templates. -->
        {% block mainContainer %}
        {% endblock %}
    </div>
</body>
</html>

leadsDatabase/templates/leadsDatabase/index.html
{% extends "leadsDatabase/base.html" %}

<!-- Content of the welcome page. -->
{% block mainContainer %}
    
    <div class="welcomePageLinksContainer">
        <a class="welcomePageLinks" href='{% url "leadsDatabase:list" %}'>List all available leads</a>
    </div>
    <div class="welcomePageLinksContainer">
        <a class="welcomePageLinks" href='{% url "leadsDatabase:add" %}'>Add new lead</a>
    </div>

{% endblock %}

leadsDatabase/templates/leadsDatabase/inputButtons.html
<!-- HTML of the input buttons, which are used in multiple child templates. -->
<form action='{% url "leadsDatabase:add" %}'>
    <input id="inputButtonAddLead"  type="submit" value="Add another lead" />
</form>
<form action='{% url "leadsDatabase:index" %}'>
    <input id="inputButtonGoBack"  type="submit" value="Go back to main page" />
</form>
        
        

leadsDatabase/templates/leadsDatabase/list.html
{% extends "leadsDatabase/base.html" %}

<!-- Content of the table of the current leads. -->
{% block mainContainer %}

    {% if leads %}
        <table class="leadsTable">
            <tr>
                <th class="leadTableHeaders">Name</th>
                <th class="leadTableHeaders">Email adress</th>
            </tr>
            <!-- Loops through all available leads and adds a table entry for each one. -->
            {% for lead in leads %}
                <tr>
                    <td class="leadTableEntries">{{ lead.name_text }}</td>
                    <td class="leadTableEntries">{{ lead.email_text }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p class="leadsTable">No leads are available.</p>
    {% endif %}
    <!-- Includes the buttons to add another lead or go back to the welcome page. -->
    {% include 'leadsDatabase/inputButtons.html' %}

{% endblock %}